### ISSUE TITLE
Wrong CMake set syntax

### ISSUE THREAD

**Issue by Fytch** [eliasdaler/imgui-sfml-fetchcontent#1]
Your usage of ```set``` in the file ```imgui-sfml-fetchcontent/dependencies/sfml/CMakeLists.txt``` is wrong. Instead of ```set(SFML_BUILD_AUDIO CACHE BOOL FALSE)```, it should be ```set(SFML_BUILD_AUDIO FALSE CACHE BOOL "")``` ([source](https://cmake.org/cmake/help/latest/command/set.html#set-cache-entry)). Alternatively, you may also use ```option(SFML_BUILD_AUDIO "" FALSE)```.

This is likely wrong in even more places than just the one I've highlighted.

**Comment by eliasdaler** [comment]
Thanks, fixed!
I don't want to use `option`, because while it does the same, it looks confusing, because you expect the `option` to be some sort of public option, not a "hack" to override default option values in dependencies.

**Comment by ascii78** [comment]
also include the empty quotes "", my cmake 3.18 errors out without them, these are docstrings for describing the setting in more detail.

**Comment by eliasdaler** [comment]
Hmm, this seems like a breaking change in newer CMake version. Will take a look into it, thanks
