### ISSUE TITLE
unresolved external

### ISSUE THREAD

**Issue by Laguna1989** [eliasdaler/imgui-sfml-fetchcontent#2]
Hi and thanks for providing this demo. Unfortunately I get an undefined reference, when I execute the commands from the readme.
running `cmake version 3.21.3` and  `g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`.

```
/usr/bin/ld: CMakeFiles/imgui-sfml-example.dir/main.cpp.o: in function `main':
main.cpp:(.text+0x225): undefined reference to `ImGui::ShowDemoWindow(bool*)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/imgui-sfml-example.dir/build.make:107: src/imgui-sfml-example] Error 1
make[1]: *** [CMakeFiles/Makefile2:373: src/CMakeFiles/imgui-sfml-example.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

I tried to add a dependency  `imgui` for the target `imgui-sfml-example`, but it seems that there is no imgui library available.

**Comment by Laguna1989** [comment]
What seems to work is to add `${imgui_SOURCE_DIR}/imgui_demo.cpp` to the list of source files of the `imgui-sfml-example` target. Not sure if this is the intended solution?

**Comment by eliasdaler** [comment]
Hello. Can you please test the 'dev' branch?
I think that I encountered this issue too - `IMGUI_SFML_IMGUI_DEMO` wasn't being set to `ON` in the method used in `master` branch

**Comment by Laguna1989** [comment]
Works like a charm, thank you 👍
