### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by CharlesBunders** [eliasdaler/imgui-sfml-fetchcontent#4]
When I build on Windows and run the example the libraries are not found. I had to copy manually the various built libraries to the directory of the .exe for everything to work. Is there something I can pass to CMake to get these libraries to be found with out the copy? 

This is with Visual Studio 2022 and I did the build from the command line with CMake as well (FYI).

**Comment by eliasdaler** [comment]
The only thing you can do is do something like this for shared library build:

```cmake
add_custom_command(TARGET example_glfw_opengl2 POST_BUILD
      COMMAND ${CMAKE_COMMAND} -E copy_if_different
          {DLLS_NEEDED}
          $<TARGET_FILE_DIR:your_program>
)
```

**Comment by CharlesBunders** [comment]
For anyone looking, another way is to use static instead of shared libraries:

`cmake .. -D LINK_DEPS_STATIC=ON -D BUILD_SHARED_LIBS=FALSE
`

**Comment by eliasdaler** [comment]
CMake 3.21 also added `TARGET_RUNTIME_DLLS` which can make this easier.

https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#genex:TARGET_RUNTIME_DLLS
