### ISSUE TITLE
Change ImGui-SFML branch to `2.6.x`

### ISSUE THREAD

**Issue by ChrisThrasher** [eliasdaler/imgui-sfml-fetchcontent#5]
ImGui-SFML now uses SFML's branching strategy where `master` represents v3 and `2.6.x` represents the 2.6 series.

https://github.com/SFML/cmake-sfml-project/compare/master...imgui-sfml

By the way I also have this branch in the official CMake template which shows how to add ImGui-SFML.

**Comment by eliasdaler** [comment]
Done, thanks!
